# Libraries

In [9]:
import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo
from sklearn.datasets import fetch_california_housing

from tensorflow.keras import layers, models

from sklearn.metrics import confusion_matrix, f1_score, classification_report, accuracy_score, balanced_accuracy_score, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold

# Data

## Classification

In [8]:
breast_cancer = fetch_ucirepo(id=17)

bcwd_df = pd.concat(
    [breast_cancer.data.features, breast_cancer.data.targets],
    axis=1
)
bcwd_df.head()

   radius1  texture1  perimeter1   area1  ...  concave_points3  symmetry3  fractal_dimension3  Diagnosis
0    17.99     10.38      122.80  1001.0  ...           0.2654     0.4601             0.11890          M
1    20.57     17.77      132.90  1326.0  ...           0.1860     0.2750             0.08902          M
2    19.69     21.25      130.00  1203.0  ...           0.2430     0.3613             0.08758          M
3    11.42     20.38       77.58   386.1  ...           0.2575     0.6638             0.17300          M
4    20.29     14.34      135.10  1297.0  ...           0.1625     0.2364             0.07678          M

[5 rows x 31 columns]

In [7]:
adult = fetch_ucirepo(id=2)
adult_df = pd.concat(
    [adult.data.features, adult.data.targets],
    axis=1
)
adult_df.head()

   age         workclass  fnlwgt  education  ...  capital-loss hours-per-week native-country income
0   39         State-gov   77516  Bachelors  ...             0             40  United-States  <=50K
1   50  Self-emp-not-inc   83311  Bachelors  ...             0             13  United-States  <=50K
2   38           Private  215646    HS-grad  ...             0             40  United-States  <=50K
3   53           Private  234721       11th  ...             0             40  United-States  <=50K
4   28           Private  338409  Bachelors  ...             0             40           Cuba  <=50K

[5 rows x 15 columns]

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz"

higgs_df = pd.read_csv(
    url,
    compression="gzip",
    header=None,
    nrows=500_000
)

higgs_df.head()

## Regression

In [ ]:
california = fetch_california_housing(as_frame=True)
california_df = california.frame
california_df.head()

In [ ]:
concrete_compressive_strength = fetch_ucirepo(id=165) 
ccs_df = pd.concat(
    [concrete_compressive_strength.data.features, concrete_compressive_strength.data.targets],
    axis=1
)
ccs_df.head()

In [ ]:
seoul_bike_sharing_demand = fetch_ucirepo(id=560)
sbsd_df = pd.concat(
    [seoul_bike_sharing_demand.data.features, seoul_bike_sharing_demand.data.targets],
    axis=1
)
sbsd_df.head()

# Models